# Generated by Django 6.0.4 on 2026-04-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consumo', models.DateField(verbose_name='Data Consumo')),
                ('local', models.CharField(choices=[('SEDE', 'Cantina da Sede'), ('SECADOR', 'Cantina do Secador')], default='SEDE', max_length=50)),
                ('qtd_cafe', models.IntegerField(default=0)),
                ('qtd_almoco_buffet', models.IntegerField(default=0)),
                ('qtd_almoco_marmita', models.IntegerField(default=0)),
                ('qtd_janta', models.IntegerField(default=0)),
                ('qtd_lanche', models.IntegerField(default=0)),
                ('valor_cafe', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('valor_almoco', models.DecimalField(decimal_places=2, default=24.0, max_digits=5)),
                ('valor_almoco_marmita', models.DecimalField(decimal_places=2, default=21.5, max_digits=5)),
                ('valor_janta', models.DecimalField(decimal_places=2, default=21.5, max_digits=5)),
                ('valor_lanche', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
            ],
        ),
    ]
