# Generated by Django 6.0.4 on 2026-04-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorefeicao',
            name='setor',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Setor/Categoria'),
        ),
    ]
