# Generated by Django 6.0.4 on 2026-04-15 23:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0002_registrorefeicao_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.DecimalField(decimal_places=2, default=9.0, max_digits=5, verbose_name="Caf'da Manhã")),
                ('buffet', models.DecimalField(decimal_places=2, default=24.0, max_digits=5, verbose_name='Almoço Buffet')),
                ('marmita', models.DecimalField(decimal_places=2, default=21.5, max_digits=5, verbose_name='Almoço Marmita')),
                ('janta', models.DecimalField(decimal_places=2, default=21.5, max_digits=5, verbose_name='Janta')),
                ('lanche', models.DecimalField(decimal_places=2, default=9.0, max_digits=5, verbose_name='Lanche')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tabela Preço',
                'verbose_name_plural': 'Tabela Preços',
            },
        ),
        migrations.AlterModelOptions(
            name='registrorefeicao',
            options={'ordering': ('-data_consumo', '-id'), 'verbose_name': 'Registro de Refeição', 'verbose_name_plural': 'Registros de Refeições'},
        ),
        migrations.AddField(
            model_name='registrorefeicao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total Gasto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='data_consumo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Consumo'),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='local',
            field=models.CharField(choices=[('SEDE', 'Cantina da Sede'), ('SECADOR', 'Cantina da Secador')], default='SEDE', max_length=50, verbose_name='Cantina'),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='qtd_almoco_buffet',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd. Buffet'),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='qtd_almoco_marmita',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd. Marmita'),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='qtd_cafe',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd. Café'),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='qtd_janta',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd. Janta'),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='qtd_lanche',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd. Lanche'),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='setor',
            field=models.CharField(choices=[('Colaborador secador', 'Colaborador secador'), ('Colaborador algodoeira', 'Colaborador algodoeira'), ('Terceirizado algodoeira', 'Terceirizado algodoeira'), ('Safrista algodoeira', 'Safrista algodoeira'), ('Corporativo', 'Corporativo'), ('Colaborador sede', 'Colaborador sede'), ('Corporativo sede', 'Corporativo sede'), ('Terceiros Fazenda', 'Terceiros Fazenda')], default='Colaborador sede', max_length=100, verbose_name='Setor/Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='valor_almoco',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='valor_almoco_marmita',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='valor_cafe',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='valor_janta',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='valor_lanche',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
