# Generated by Django 6.0.4 on 2026-08-22 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0003_tabelapreco_alter_registrorefeicao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Fazenda')),
            ],
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='local',
            field=models.CharField(choices=[('SEDE', 'Cantina da Sede'), ('SECADOR', 'Cantina do Secador'), ('CANTINA_MATAO', 'Cantina Matão'), ('CANTINA_BC', 'Cantina BC'), ('CANTINA_LAGOA', 'Cantina Lagoa')], default='SEDE', max_length=50, verbose_name='Cantina'),
        ),
        migrations.AlterField(
            model_name='registrorefeicao',
            name='setor',
            field=models.CharField(choices=[('Colaborador secador', 'Colaborador Secador'), ('Colaborador algodoeira', 'Colaborador Algodoeira'), ('Colaborador escritorio', 'Colaborador Escritório'), ('Terceirizado algodoeira', 'Terceirizado Algodoeira'), ('Safrista algodoeira', 'Safrista Algodoeira'), ('Safrista secador', 'Safrista Secador'), ('Corporativo', 'Corporativo'), ('Colaborador Sede', 'Colaborador Sede'), ('Corporativo sede', '(Não utilizar) Corporativo Sede'), ('Terceiros Fazenda', 'Terceirizado Sede'), ('Terceiros', 'Terceiros')], max_length=100, verbose_name='Setor/Categoria'),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='cafe',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5, verbose_name='Café da Manhã'),
        ),
        migrations.AddField(
            model_name='registrorefeicao',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refeicoes.fazenda', verbose_name='Fazenda'),
        ),
        migrations.AddField(
            model_name='tabelapreco',
            name='fazenda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refeicoes.fazenda', verbose_name='Fazenda'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dono', models.BooleanField(default=False, verbose_name='É Administrador? (Acesso Total)')),
                ('fazenda_lotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='refeicoes.fazenda', verbose_name='Fazenda do RH')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
