# Generated by Django 6.0.4 on 2026-08-28 14:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0004_fazenda_alter_registrorefeicao_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelapreco',
            name='buffet',
            field=models.DecimalField(decimal_places=2, default=24.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Almoço Buffet'),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='cafe',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Café da Manhã'),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='janta',
            field=models.DecimalField(decimal_places=2, default=21.5, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Janta'),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='lanche',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='marmita',
            field=models.DecimalField(decimal_places=2, default=21.5, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Almoço Marmita'),
        ),
    ]
